(function(){
  const $ = (s, r=document) => r.querySelector(s);
  const $$ = (s, r=document) => Array.from(r.querySelectorAll(s));
  const page = document.body.dataset.page || '';
  $$('.links a, .bottom-nav a').forEach(a => { if(a.dataset.nav === page) a.classList.add('active'); });
  const hamb = $('.hamb'), links = $('.links');
  if(hamb && links) hamb.addEventListener('click', () => links.classList.toggle('open'));

  const get = k => { try { return JSON.parse(localStorage.getItem(k) || '[]'); } catch(e){ return []; } };
  const set = (k,v) => localStorage.setItem(k, JSON.stringify(v));
  const fmt = () => new Date().toLocaleString('en-IN');
  const makeId = p => p + '-' + Date.now().toString().slice(-7);
  const ageFromDob = dob => { if(!dob) return 0; const b=new Date(dob), t=new Date(); let a=t.getFullYear()-b.getFullYear(); const m=t.getMonth()-b.getMonth(); if(m<0 || (m===0 && t.getDate()<b.getDate())) a--; return a; };
  function readFileAsDataURL(input){ return new Promise(resolve=>{ if(!input || !input.files || !input.files[0]) return resolve(''); const r=new FileReader(); r.onload=()=>resolve(r.result); r.readAsDataURL(input.files[0]); }); }
  function initials(name, fallback='TM'){ return (name||fallback).split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase() || fallback; }

  const sampleTeams = [
    {id:'team-bhopal', name:'Bhopal Strikers', city:'Bhopal', owner:'Captain Coming Soon', status:'Player Auction Pending', logo:'', squadBanner:''},
    {id:'team-indore', name:'Indore Warriors', city:'Indore', owner:'Captain Coming Soon', status:'Player Auction Pending', logo:'', squadBanner:''},
    {id:'team-gwalior', name:'Gwalior Royals', city:'Gwalior', owner:'Captain Coming Soon', status:'Player Auction Pending', logo:'', squadBanner:''}
  ];
  function getTeams(){ const teams=get('tmpclTeams'); return teams.length ? teams : sampleTeams; }
  const defaultNews = [{id:'news-opening-ceremony-01-jun', tag:'Opening Ceremony', title:'TMPCL Opening Ceremony on 01 June', summary:'TMPCL ki grand opening ceremony 01 June ko hogi. League updates, team presentation aur event moments yahin publish honge.', date:'2026-06-01', image:''}];
  function getNewsItems(){ if(localStorage.getItem('tmpclNews')===null) set('tmpclNews', defaultNews); return get('tmpclNews'); }
  const getPartners = () => get('tmpclPartners');

  function openSquadBanner(team){
    $('#squadBannerModal')?.remove();
    const modal=document.createElement('div');
    modal.id='squadBannerModal'; modal.className='squad-banner-modal';
    modal.innerHTML=`<div class="squad-modal-backdrop" data-close-squad="1"></div><div class="squad-modal-card"><button class="squad-modal-close" data-close-squad="1" type="button">×</button><div class="squad-modal-head"><div><small>Official Squad Banner</small><h3>${team.name}</h3><p>${team.city||''} · ${team.status||'Player Auction Pending'}</p></div></div>${team.squadBanner?`<img class="squad-banner-img" src="${team.squadBanner}" alt="${team.name} squad banner">`:`<div class="squad-banner-placeholder"><div class="team-logo-box big"><span>${initials(team.name)}</span></div><h3>Squad Banner Coming Soon</h3><p>Player Auction complete hone ke baad TMPCL Team se squad banner/poster upload karne par yahan show hoga.</p></div>`}<div class="squad-modal-actions"><button class="btn ghost" data-close-squad="1" type="button">Close</button>${team.squadBanner?`<a class="btn" href="${team.squadBanner}" target="_blank" rel="noopener">View Full Size</a>`:''}</div></div>`;
    document.body.appendChild(modal);
    modal.querySelectorAll('[data-close-squad]').forEach(el=>el.addEventListener('click',()=>modal.remove()));
  }

  function renderPublicTeams(){
    const grid=$('#teamsGrid'); if(!grid) return;
    const teams=getTeams();
    grid.innerHTML=teams.map(team=>{ const logo=team.logo?`<img src="${team.logo}" alt="${team.name} logo">`:`<span>${initials(team.name)}</span>`; return `<article class="team-card" data-team-id="${team.id}"><div class="team-card-head"><div class="team-logo-box">${logo}</div><div><h3>${team.name}</h3><div class="team-city">${team.city||''}</div><span class="team-status">${team.status||'Player Auction Pending'}</span></div></div><div class="team-meta-row"><div class="team-meta"><strong>18</strong><span>Total Squad</span></div><div class="team-meta"><strong>A-5</strong><span>Category A</span></div><div class="team-meta"><strong>D-3</strong><span>Only U19</span></div></div><button class="btn ghost team-toggle" type="button">View Squad</button></article>`; }).join('');
    $$('.team-card', grid).forEach(card=>card.addEventListener('click',()=>{ const team=getTeams().find(t=>t.id===card.dataset.teamId); if(team) openSquadBanner(team); }));
  }
  renderPublicTeams();

  function renderPublicPartners(){
    const grid=$('#publishedPartnersGrid'); if(!grid) return;
    const published=getPartners().filter(p=>(p.status||'Published')==='Published');
    const empty=$('#partnersEmpty'); if(empty) empty.style.display=published.length?'none':'block';
    grid.innerHTML=published.map(p=>{ const logo=p.logo?`<img src="${p.logo}" alt="${p.name} logo">`:`<span>${initials(p.name,'TP')}</span>`; const link=p.link?`<a href="${p.link}" target="_blank" rel="noopener" class="mini-btn">Visit Link</a>`:''; return `<article class="partner-public-card"><div class="partner-public-logo">${logo}</div><div><span class="tag">${p.category||'Partner'}</span><h3>${p.name}</h3><p>${p.description||'Official TMPCL partner.'}</p>${link}</div></article>`; }).join('');
  }
  renderPublicPartners();

  const regFee=$('#regFee'), regTotal=$('#regTotal'); if(regFee) regFee.textContent='₹999'; if(regTotal) regTotal.textContent='₹999';
  const regForm=$('#registrationForm');
  if(regForm){ regForm.addEventListener('submit', e=>{ e.preventDefault(); const data=Object.fromEntries(new FormData(regForm).entries()); const age=ageFromDob(data.dob); const photo=regForm.querySelector('input[name="photo"]'); const aadhaar=regForm.querySelector('input[name="aadhaar"]'); if(!data.dob){ alert('Date of Birth mandatory hai.'); return; } if(!photo || !photo.files.length){ alert('Player photo upload mandatory hai.'); return; } if(!aadhaar || !aadhaar.files.length){ alert('Aadhaar Card / Age Proof upload mandatory hai.'); return; } if(data.ageGroup==='U19' && age>19){ alert('U19 age group ke liye Date of Birth ke hisab se age 19 ya usse kam honi chahiye.'); return; } const entry={...data,id:makeId('TMPCL'),date:fmt(),fee:999,age,assignedCategory:'Pending until trials & auction',photoFile:photo.files[0].name,aadhaarFile:aadhaar.files[0].name}; const regs=get('tmpclRegs'); regs.unshift(entry); set('tmpclRegs',regs); const success=$('#regSuccess'); if(success){ success.style.display='block'; success.innerHTML=`<strong>Registration successful!</strong><br>Registration ID: <strong>${entry.id}</strong><br>Amount: ₹999`; } regForm.reset(); }); }

  const contactForm=$('#contactForm');
  if(contactForm){ contactForm.addEventListener('submit', e=>{ e.preventDefault(); const data=Object.fromEntries(new FormData(contactForm).entries()); const msgs=get('tmpclMessages'); msgs.unshift({...data,date:fmt()}); set('tmpclMessages',msgs); const s=$('#contactSuccess'); if(s){ s.style.display='block'; s.innerHTML='<strong>Message sent successfully.</strong> TMPCL Team will contact you soon.'; } contactForm.reset(); }); }

  const partnerForm=$('#partnerForm');
  if(partnerForm){ partnerForm.addEventListener('submit', e=>{ e.preventDefault(); const data=Object.fromEntries(new FormData(partnerForm).entries()); const all=get('tmpclPartnerMessages'); all.unshift({...data,date:fmt()}); set('tmpclPartnerMessages',all); const s=$('#partnerSuccess'); if(s){ s.style.display='block'; s.innerHTML='<strong>Partnership enquiry submitted.</strong> TMPCL Team will contact you soon.'; } partnerForm.reset(); }); }

  const newsList=$('#newsList');
  if(newsList){ const empty=$('#newsEmpty'); const posts=getNewsItems(); if(empty) empty.style.display=posts.length?'none':'block'; newsList.innerHTML=posts.map(p=>{ const img=p.image?`<div class="thumb news-thumb-img" style="background-image:linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.55)),url('${p.image}')"></div>`:`<div class="thumb"></div>`; const date=p.date?`<small class="muted">${p.date}</small>`:''; return `<article class="card news-card">${img}<div><span class="tag">${p.tag||'Update'}</span><h3>${p.title}</h3>${date}<p>${p.summary||''}</p></div></article>`; }).join(''); }

  const galleryGrid=$('#galleryGrid');
  if(galleryGrid){ const empty=$('#galleryEmpty'), modal=$('#galleryModal'), title=$('#galleryModalTitle'), visual=modal?modal.querySelector('.gallery-modal-visual'):null, desc=modal?modal.querySelector('p'):null; const allItems=get('tmpclGallery'); function card(item){ const bg=item.image?`style="background-image:linear-gradient(180deg,rgba(0,0,0,.12),rgba(0,0,0,.76)),url('${item.image}')"`:''; const play=item.type==='videos'||item.url?'<div class="play">▶</div>':''; const date=item.date?`<p>${item.date}</p>`:'<p>TMPCL published media</p>'; return `<article class="card media-card" data-id="${item.id}" data-type="${item.category}" ${bg}>${play}<div class="label"><span class="tag">${item.category}</span><h3>${item.title}</h3>${date}</div></article>`; } function render(filter='all'){ const items=allItems.filter(item=>filter==='all'||item.category===filter||(filter==='videos'&&item.type==='videos')); galleryGrid.innerHTML=items.map(card).join(''); if(empty) empty.style.display=allItems.length?'none':'block'; $$('.media-card',galleryGrid).forEach(c=>c.addEventListener('click',()=>{ const item=allItems.find(g=>g.id===c.dataset.id); if(!item||!modal) return; if(title) title.textContent=item.title||'TMPCL Media'; if(visual){ visual.innerHTML=item.type==='videos'||item.url?'<div class="play modal-play">▶</div>':''; visual.style.backgroundImage=item.image?`linear-gradient(180deg,rgba(0,0,0,.05),rgba(0,0,0,.55)),url('${item.image}')`:''; visual.style.backgroundSize='cover'; visual.style.backgroundPosition='center'; } if(desc) desc.innerHTML=item.url?`<a class="btn" href="${item.url}" target="_blank" rel="noopener">Open Video / Link →</a>`:'Published TMPCL media preview.'; modal.classList.add('open'); })); } $$('.filter').forEach(btn=>btn.addEventListener('click',()=>{ $$('.filter').forEach(b=>b.classList.remove('active')); btn.classList.add('active'); render(btn.dataset.filter); })); $$('.gallery-modal-close,[data-gallery-close]').forEach(btn=>btn.addEventListener('click',()=>modal&&modal.classList.remove('open'))); render(); }

  const teamLoginForm=$('#adminLoginForm');
  if(teamLoginForm){ teamLoginForm.addEventListener('submit', e=>{ e.preventDefault(); const data=Object.fromEntries(new FormData(teamLoginForm).entries()); if(data.username==='team' && data.password==='tmpcl123'){ sessionStorage.setItem('tmpclTeamAccess','1'); location.href='admin-dashboard.html'; } else { const er=$('#adminLoginError'); if(er){ er.style.display='block'; er.textContent='Invalid login. Use team / tmpcl123'; } } }); }

  if($('#regTable')){
    if(sessionStorage.getItem('tmpclTeamAccess')!=='1'){ location.href='admin-login.html'; return; }
    function renderDashboard(){
      const regs=get('tmpclRegs'), msgs=get('tmpclMessages'), teams=getTeams(), galleryItems=get('tmpclGallery'), newsItems=getNewsItems(), partnerItems=getPartners(), partnerEnquiries=get('tmpclPartnerMessages');
      $('#statRegistrations').textContent=regs.length; $('#statTeams')&&($('#statTeams').textContent=teams.length); $('#statSquadBanners')&&($('#statSquadBanners').textContent=teams.filter(t=>!!t.squadBanner).length); $('#statU19')&&($('#statU19').textContent=regs.filter(r=>r.ageGroup==='U19'||Number(r.age)<=19).length); $('#statGallery')&&($('#statGallery').textContent=galleryItems.length); $('#statNews')&&($('#statNews').textContent=newsItems.length); $('#statPartners')&&($('#statPartners').textContent=partnerItems.filter(p=>(p.status||'Published')==='Published').length); $('#statPartnerEnquiries')&&($('#statPartnerEnquiries').textContent=partnerEnquiries.length); $('#statContactEnquiries')&&($('#statContactEnquiries').textContent=msgs.length);
      const pb=$('#partnersAdminTable tbody'); if(pb){ $('#emptyPartnersAdmin').style.display=partnerItems.length?'none':'block'; pb.innerHTML=partnerItems.map(item=>{ const preview=item.logo?`<img src="${item.logo}" style="width:60px;height:42px;border-radius:10px;object-fit:contain;background:#fff;padding:4px">`:`<span class="badge muted-badge">${initials(item.name,'TP')}</span>`; const link=item.link?`<a class="mini-btn" href="${item.link}" target="_blank" rel="noopener">Open</a>`:`<span class="muted">—</span>`; return `<tr><td>${preview}</td><td>${item.name}</td><td>${item.category||''}</td><td>${item.status||'Published'}</td><td>${link}</td><td>${item.description||''}</td><td><div class="admin-table-actions"><button class="mini-btn" data-edit-partner="${item.id}">Edit</button><button class="mini-btn danger" data-delete-partner="${item.id}">Delete</button></div></td></tr>`; }).join(''); $$('[data-edit-partner]',pb).forEach(btn=>btn.addEventListener('click',()=>{ const item=partnerItems.find(p=>p.id===btn.dataset.editPartner); if(!item) return; $('#partnerId').value=item.id; $('#partnerName').value=item.name||''; $('#partnerCategory').value=item.category||'Title Sponsor'; $('#partnerLink').value=item.link||''; $('#partnerDescription').value=item.description||''; $('#partnerStatus').value=item.status||'Published'; const s=$('#partnerManageSuccess'); if(s){s.style.display='block'; s.innerHTML='<strong>Edit mode:</strong> Change fields and click Publish / Update Partner. Existing logo will remain unless you upload a new one.';} window.scrollTo({top:0,behavior:'smooth'}); })); $$('[data-delete-partner]',pb).forEach(btn=>btn.addEventListener('click',()=>{ if(!confirm('Delete this partner?')) return; set('tmpclPartners', partnerItems.filter(p=>p.id!==btn.dataset.deletePartner)); renderDashboard(); })); }
      const pe=$('#partnerEnquiriesTable tbody'); if(pe){ $('#emptyPartnerEnquiries').style.display=partnerEnquiries.length?'none':'block'; pe.innerHTML=partnerEnquiries.map(m=>`<tr><td>${m.name||''}</td><td>${m.brand||''}</td><td>${m.category||''}</td><td>${m.mobile||''}</td><td>${m.email||''}</td><td>${m.message||''}</td><td>${m.date||''}</td></tr>`).join(''); }
      const tb=$('#adminTeamsTable tbody'); if(tb){ $('#emptyTeams').style.display=teams.length?'none':'block'; tb.innerHTML=teams.map(t=>{ const logo=t.logo?`<img src="${t.logo}" style="width:42px;height:42px;border-radius:12px;object-fit:cover">`:`<strong>${initials(t.name)}</strong>`; const banner=t.squadBanner?`<span class="badge ok">Uploaded</span>`:`<span class="badge muted-badge">Not Added</span>`; return `<tr><td>${logo}</td><td>${t.name}</td><td>${t.city||''}</td><td>${t.owner||''}</td><td>${t.status||''}</td><td>${banner}</td><td><div class="admin-table-actions"><button class="mini-btn" data-edit-team="${t.id}">Edit</button><button class="mini-btn" data-preview-team="${t.id}">Preview</button><button class="mini-btn danger" data-delete-team="${t.id}">Delete</button></div></td></tr>`; }).join(''); $$('[data-edit-team]',tb).forEach(btn=>btn.addEventListener('click',()=>{ const team=teams.find(t=>t.id===btn.dataset.editTeam); if(!team) return; $('#teamId').value=team.id; $('#teamName').value=team.name; $('#teamCity').value=team.city||''; $('#teamOwner').value=team.owner||''; $('#teamStatus').value=team.status||'Player Auction Pending'; const s=$('#teamSuccess'); if(s){s.style.display='block'; s.innerHTML='<strong>Edit mode:</strong> Change fields and click Save / Update Team. Existing logo/banner will remain unless you upload new files.';} window.scrollTo({top:0,behavior:'smooth'}); })); $$('[data-preview-team]',tb).forEach(btn=>btn.addEventListener('click',()=>{ const team=teams.find(t=>t.id===btn.dataset.previewTeam); if(team) openSquadBanner(team); })); $$('[data-delete-team]',tb).forEach(btn=>btn.addEventListener('click',()=>{ if(!confirm('Delete this team?')) return; set('tmpclTeams',teams.filter(t=>t.id!==btn.dataset.deleteTeam)); renderDashboard(); })); }
      const gb=$('#galleryAdminTable tbody'); if(gb){ $('#emptyGalleryAdmin').style.display=galleryItems.length?'none':'block'; gb.innerHTML=galleryItems.map(item=>{ const preview=item.image?`<img src="${item.image}" style="width:60px;height:42px;border-radius:10px;object-fit:cover">`:`<span class="badge muted-badge">No Image</span>`; const link=item.url?`<a class="mini-btn" href="${item.url}" target="_blank" rel="noopener">Open</a>`:`<span class="muted">—</span>`; return `<tr><td>${preview}</td><td>${item.title}</td><td>${item.type}</td><td>${item.category}</td><td>${item.date||''}</td><td>${link}</td><td><div class="admin-table-actions"><button class="mini-btn" data-edit-media="${item.id}">Edit</button><button class="mini-btn danger" data-delete-media="${item.id}">Delete</button></div></td></tr>`; }).join(''); $$('[data-edit-media]',gb).forEach(btn=>btn.addEventListener('click',()=>{ const item=galleryItems.find(g=>g.id===btn.dataset.editMedia); if(!item) return; $('#mediaId').value=item.id; $('#mediaTitle').value=item.title||''; $('#mediaType').value=item.type||'photos'; $('#mediaCategory').value=item.category||'events'; $('#mediaDate').value=item.date||''; $('#mediaUrl').value=item.url||''; const s=$('#gallerySuccess'); if(s){s.style.display='block'; s.innerHTML='<strong>Edit mode:</strong> Change fields and click Publish / Update Media. Existing image will remain unless you upload a new one.';} window.scrollTo({top:0,behavior:'smooth'}); })); $$('[data-delete-media]',gb).forEach(btn=>btn.addEventListener('click',()=>{ if(!confirm('Delete this gallery media?')) return; set('tmpclGallery',galleryItems.filter(g=>g.id!==btn.dataset.deleteMedia)); renderDashboard(); })); }
      const nb=$('#newsAdminTable tbody'); if(nb){ $('#emptyNewsAdmin').style.display=newsItems.length?'none':'block'; nb.innerHTML=newsItems.map(item=>{ const preview=item.image?`<img src="${item.image}" style="width:60px;height:42px;border-radius:10px;object-fit:cover">`:`<span class="badge muted-badge">No Image</span>`; return `<tr><td>${preview}</td><td>${item.title}</td><td>${item.tag||''}</td><td>${item.date||''}</td><td>${item.summary||''}</td><td><div class="admin-table-actions"><button class="mini-btn" data-edit-news="${item.id}">Edit</button><button class="mini-btn danger" data-delete-news="${item.id}">Delete</button></div></td></tr>`; }).join(''); $$('[data-edit-news]',nb).forEach(btn=>btn.addEventListener('click',()=>{ const item=newsItems.find(n=>n.id===btn.dataset.editNews); if(!item) return; $('#newsId').value=item.id; $('#newsTitle').value=item.title||''; $('#newsTag').value=item.tag||'Announcement'; $('#newsDate').value=item.date||''; $('#newsSummary').value=item.summary||''; const s=$('#newsSuccess'); if(s){s.style.display='block'; s.innerHTML='<strong>Edit mode:</strong> Change fields and click Publish / Update News. Existing image will remain unless you upload a new one.';} window.scrollTo({top:0,behavior:'smooth'}); })); $$('[data-delete-news]',nb).forEach(btn=>btn.addEventListener('click',()=>{ if(!confirm('Delete this news update?')) return; set('tmpclNews',newsItems.filter(n=>n.id!==btn.dataset.deleteNews)); renderDashboard(); })); }
      const rb=$('#regTable tbody'); if(rb){ $('#emptyRegs').style.display=regs.length?'none':'block'; rb.innerHTML=regs.map(r=>`<tr><td>${r.id}</td><td>${r.name||''}</td><td>${r.mobile||''}</td><td>${r.city||''}</td><td>${r.dob||''}</td><td>${r.age||''}</td><td>${r.role||''}</td><td>${r.ageGroup||''}</td><td>${r.assignedCategory||'Pending until trials & auction'}</td><td>${r.photoFile||''}</td><td>${r.aadhaarFile||''}</td><td>₹${r.fee||''}</td><td>${r.date||''}</td></tr>`).join(''); }
      const mb=$('#msgTable tbody'); if(mb){ $('#emptyMsgs').style.display=msgs.length?'none':'block'; mb.innerHTML=msgs.map(m=>`<tr><td>${m.name||''}</td><td>${m.mobile||''}</td><td>${m.email||''}</td><td>${m.enquiryType||m.subject||'General Support'}</td><td>${m.message||''}</td><td>${m.date||''}</td></tr>`).join(''); }
    }

    const partnerManageForm=$('#partnerManageForm');
    if(partnerManageForm){ partnerManageForm.addEventListener('submit', async e=>{ e.preventDefault(); const fd=new FormData(partnerManageForm); const partnerId=fd.get('partnerId')||('partner-'+Date.now()); const items=getPartners(); const existing=items.find(p=>p.id===partnerId); const logoData=await readFileAsDataURL($('#partnerLogo')); const partner={id:partnerId,name:fd.get('partnerName'),category:fd.get('partnerCategory')||'Partner',link:fd.get('partnerLink')||'',description:fd.get('partnerDescription')||'',status:fd.get('partnerStatus')||'Published',logo:logoData||(existing&&existing.logo)||''}; const updated=items.filter(p=>p.id!==partnerId); updated.unshift(partner); set('tmpclPartners',updated); const s=$('#partnerManageSuccess'); if(s){s.style.display='block'; s.innerHTML='<strong>Partner saved successfully.</strong> Published partners public Partners page par show honge.';} partnerManageForm.reset(); $('#partnerId').value=''; renderDashboard(); }); $('#partnerFormReset')?.addEventListener('click',()=>{ partnerManageForm.reset(); $('#partnerId').value=''; const s=$('#partnerManageSuccess'); if(s) s.style.display='none'; }); }
    const teamForm=$('#teamForm');
    if(teamForm){ teamForm.addEventListener('submit', async e=>{ e.preventDefault(); const fd=new FormData(teamForm); const teamId=fd.get('teamId')||('team-'+Date.now()); const teams=get('tmpclTeams').length?get('tmpclTeams'):getTeams(); const existing=teams.find(t=>t.id===teamId); const logoData=await readFileAsDataURL($('#teamLogo')); const bannerData=await readFileAsDataURL($('#squadBanner')); const obj={id:teamId,name:fd.get('teamName'),city:fd.get('teamCity'),owner:fd.get('teamOwner')||'',status:fd.get('teamStatus')||'Player Auction Pending',logo:logoData||(existing&&existing.logo)||'',squadBanner:bannerData||(existing&&existing.squadBanner)||''}; const updated=teams.filter(t=>t.id!==teamId); updated.unshift(obj); set('tmpclTeams',updated); const s=$('#teamSuccess'); if(s){s.style.display='block'; s.innerHTML='<strong>Team saved successfully.</strong> Public Teams page par update show hoga.';} teamForm.reset(); $('#teamId').value=''; renderDashboard(); }); $('#teamFormReset')?.addEventListener('click',()=>{ teamForm.reset(); $('#teamId').value=''; const s=$('#teamSuccess'); if(s) s.style.display='none'; }); }
    const galleryForm=$('#galleryForm');
    if(galleryForm){ galleryForm.addEventListener('submit', async e=>{ e.preventDefault(); const fd=new FormData(galleryForm); const mediaId=fd.get('mediaId')||('media-'+Date.now()); const items=get('tmpclGallery'); const existing=items.find(g=>g.id===mediaId); const imageData=await readFileAsDataURL($('#mediaImage')); const media={id:mediaId,title:fd.get('mediaTitle'),type:fd.get('mediaType')||'photos',category:fd.get('mediaCategory')||'events',date:fd.get('mediaDate')||'',url:fd.get('mediaUrl')||'',image:imageData||(existing&&existing.image)||''}; const updated=items.filter(g=>g.id!==mediaId); updated.unshift(media); set('tmpclGallery',updated); const s=$('#gallerySuccess'); if(s){s.style.display='block'; s.innerHTML='<strong>Gallery media published.</strong> Public Gallery page par card show hoga.';} galleryForm.reset(); $('#mediaId').value=''; renderDashboard(); }); $('#galleryFormReset')?.addEventListener('click',()=>{ galleryForm.reset(); $('#mediaId').value=''; const s=$('#gallerySuccess'); if(s) s.style.display='none'; }); }
    const newsForm=$('#newsForm');
    if(newsForm){ newsForm.addEventListener('submit', async e=>{ e.preventDefault(); const fd=new FormData(newsForm); const newsId=fd.get('newsId')||('news-'+Date.now()); const items=getNewsItems(); const existing=items.find(n=>n.id===newsId); const imageData=await readFileAsDataURL($('#newsImage')); const news={id:newsId,title:fd.get('newsTitle'),tag:fd.get('newsTag')||'Announcement',date:fd.get('newsDate')||'',summary:fd.get('newsSummary')||'',image:imageData||(existing&&existing.image)||''}; const updated=items.filter(n=>n.id!==newsId); updated.unshift(news); set('tmpclNews',updated); const s=$('#newsSuccess'); if(s){s.style.display='block'; s.innerHTML='<strong>News published.</strong> Public News page par card show hoga.';} newsForm.reset(); $('#newsId').value=''; renderDashboard(); }); $('#newsFormReset')?.addEventListener('click',()=>{ newsForm.reset(); $('#newsId').value=''; const s=$('#newsSuccess'); if(s) s.style.display='none'; }); }
    renderDashboard();
    $('#logoutBtn')?.addEventListener('click',()=>{ sessionStorage.removeItem('tmpclTeamAccess'); location.href='admin-login.html'; });
  }
})();

// Leadership, Founder and Selection Panel controls
(function(){
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const get=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return []}};
  const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  function initials(name,fallback='TM'){return (name||fallback).split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()||fallback}
  function readFile(input){return new Promise(resolve=>{if(!input||!input.files||!input.files[0]) return resolve(''); const r=new FileReader(); r.onload=()=>resolve(r.result); r.readAsDataURL(input.files[0]);});}
  const defaults=[
    {id:'leader-founder',name:'Founder Name',type:'Founder & League Owner',designation:'Founder & League Owner, TMPCL',bio:'TMPCL ka mission Madhya Pradesh ke tennis ball cricket talent ko professional trials, player auction aur league platform ke through bada stage dena hai.',photo:''},
    {id:'leader-head-selector',name:'Head Selector Name',type:'Head Selector',designation:'Head Selector, TMPCL Selection Committee',bio:'Trials me performance, fitness, game awareness aur potential ke basis par player evaluation aur category grading manage karenge.',photo:''},
    {id:'leader-selector-1',name:'Selector Name',type:'Selector',designation:'Selector, TMPCL Selection Committee',bio:'Player shortlisting, category grading aur player auction pool preparation me support karenge.',photo:''}
  ];
  function getLeadership(){
    if(localStorage.getItem('tmpclLeadership')===null) set('tmpclLeadership',defaults);
    return get('tmpclLeadership');
  }
  function leaderCard(p){
    const photo=p.photo?`<img src="${p.photo}" alt="${p.name}">`:`<span>${initials(p.name)}</span>`;
    return `<article class="leader-card"><div class="leader-photo">${photo}</div><div class="leader-copy"><small>${p.type||'TMPCL Leadership'}</small><h3>${p.name||'Name Coming Soon'}</h3><div class="designation">${p.designation||p.type||'TMPCL Team'}</div><p>${p.bio||'Profile details will be updated by TMPCL Team.'}</p></div></article>`;
  }
  function renderPublicLeadership(){
    const leaders=getLeadership();
    const founder=leaders.find(x=>(x.type||'').includes('Founder')) || leaders[0];
    const selectors=leaders.filter(x=>/(Selector|Coach|Advisor)/i.test(x.type||''));
    const home=$('#homeFounderCard'); if(home && founder) home.innerHTML=leaderCard(founder);
    const about=$('#aboutLeadershipGrid'); if(about){ about.innerHTML=leaders.filter(x=>(x.type||'').includes('Founder')).map(leaderCard).join('') || (founder?leaderCard(founder):''); }
    const sel=$('#selectionPanelGrid'), empty=$('#selectionPanelEmpty');
    if(sel){ sel.innerHTML=selectors.map(leaderCard).join(''); if(empty) empty.style.display=selectors.length?'none':'block'; }
  }
  renderPublicLeadership();

  function renderLeadershipAdmin(){
    const tb=$('#leadershipAdminTable tbody'); if(!tb) return;
    const items=getLeadership(); const empty=$('#emptyLeadershipAdmin'); if(empty) empty.style.display=items.length?'none':'block';
    tb.innerHTML=items.map(p=>{const photo=p.photo?`<img src="${p.photo}" alt="${p.name}">`:`<span>${initials(p.name)}</span>`; return `<tr><td><div class="leader-thumb">${photo}</div></td><td>${p.name||''}</td><td>${p.type||''}</td><td>${p.designation||''}</td><td>${p.bio||''}</td><td><div class="admin-table-actions"><button class="mini-btn" data-edit-leader="${p.id}">Edit</button><button class="mini-btn danger" data-delete-leader="${p.id}">Delete</button></div></td></tr>`;}).join('');
    $$('[data-edit-leader]',tb).forEach(btn=>btn.addEventListener('click',()=>{const p=getLeadership().find(x=>x.id===btn.dataset.editLeader); if(!p) return; $('#personId').value=p.id; $('#personName').value=p.name||''; $('#personType').value=p.type||'Selector'; $('#personDesignation').value=p.designation||''; $('#personBio').value=p.bio||''; const s=$('#leadershipSuccess'); if(s){s.style.display='block'; s.innerHTML='<strong>Edit mode:</strong> Details change karke Save / Update Profile par click karein. Existing photo tab tak rahegi jab tak new photo upload nahi karte.';} window.scrollTo({top:0,behavior:'smooth'}); }));
    $$('[data-delete-leader]',tb).forEach(btn=>btn.addEventListener('click',()=>{ if(!confirm('Delete this profile?')) return; set('tmpclLeadership',getLeadership().filter(x=>x.id!==btn.dataset.deleteLeader)); renderLeadershipAdmin(); renderPublicLeadership(); }));
  }
  const form=$('#leadershipForm');
  if(form){
    form.addEventListener('submit',async e=>{e.preventDefault(); const fd=new FormData(form); const id=fd.get('personId')||('leader-'+Date.now()); const items=getLeadership(); const existing=items.find(x=>x.id===id); const photo=await readFile($('#personPhoto')); const obj={id,name:fd.get('personName'),type:fd.get('personType'),designation:fd.get('personDesignation')||fd.get('personType'),bio:fd.get('personBio')||'',photo:photo||(existing&&existing.photo)||''}; const next=items.filter(x=>x.id!==id); next.unshift(obj); set('tmpclLeadership',next); const s=$('#leadershipSuccess'); if(s){s.style.display='block'; s.innerHTML='<strong>Profile saved successfully.</strong> Public pages par update show hoga.';} form.reset(); $('#personId').value=''; renderLeadershipAdmin(); renderPublicLeadership();});
    $('#leadershipFormReset')?.addEventListener('click',()=>{form.reset(); $('#personId').value=''; const s=$('#leadershipSuccess'); if(s) s.style.display='none';});
    renderLeadershipAdmin();
  }
})();
