-- TMPCL Supabase Database + Storage Setup
-- Run this full file once in Supabase SQL Editor before testing the website.

create table if not exists public.players (
  id text primary key,
  name text not null,
  mobile text not null,
  city text,
  dob date,
  age integer,
  age_group text,
  role text,
  batting text,
  bowling text,
  experience text,
  email text,
  photo_url text,
  proof_url text,
  fee integer default 999,
  assigned_category text default 'Pending until trials & auction',
  payment_status text default 'Pending',
  created_at timestamptz default now()
);

create table if not exists public.teams (
  id text primary key,
  name text not null,
  city text,
  owner text,
  status text default 'Player Auction Pending',
  logo_url text,
  squad_banner_url text,
  created_at timestamptz default now()
);

create table if not exists public.gallery_media (
  id text primary key,
  title text not null,
  type text default 'photos',
  category text default 'events',
  date date,
  url text,
  image_url text,
  created_at timestamptz default now()
);

create table if not exists public.news_updates (
  id text primary key,
  title text not null,
  tag text default 'Announcement',
  date date,
  summary text,
  image_url text,
  created_at timestamptz default now()
);

create table if not exists public.partners (
  id text primary key,
  name text not null,
  category text,
  link text,
  description text,
  status text default 'Published',
  logo_url text,
  created_at timestamptz default now()
);

create table if not exists public.contact_enquiries (
  id bigint generated by default as identity primary key,
  name text,
  mobile text,
  email text,
  enquiry_type text,
  message text,
  created_at timestamptz default now()
);

create table if not exists public.partner_enquiries (
  id bigint generated by default as identity primary key,
  name text,
  brand text,
  category text,
  mobile text,
  email text,
  message text,
  created_at timestamptz default now()
);

create table if not exists public.leadership_panel (
  id text primary key,
  name text not null,
  type text,
  designation text,
  bio text,
  photo_url text,
  created_at timestamptz default now()
);

alter table public.players enable row level security;
alter table public.teams enable row level security;
alter table public.gallery_media enable row level security;
alter table public.news_updates enable row level security;
alter table public.partners enable row level security;
alter table public.contact_enquiries enable row level security;
alter table public.partner_enquiries enable row level security;
alter table public.leadership_panel enable row level security;

-- Public frontend policies for the current static website version.
-- For a fully secure production launch, replace these with authenticated dashboard/backend policies.
do $$ begin
  create policy "TMPCL public select players" on public.players for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public insert players" on public.players for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public update players" on public.players for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public delete players" on public.players for delete to anon using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "TMPCL public select teams" on public.teams for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public insert teams" on public.teams for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public update teams" on public.teams for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public delete teams" on public.teams for delete to anon using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "TMPCL public select gallery" on public.gallery_media for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public insert gallery" on public.gallery_media for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public update gallery" on public.gallery_media for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public delete gallery" on public.gallery_media for delete to anon using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "TMPCL public select news" on public.news_updates for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public insert news" on public.news_updates for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public update news" on public.news_updates for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public delete news" on public.news_updates for delete to anon using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "TMPCL public select partners" on public.partners for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public insert partners" on public.partners for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public update partners" on public.partners for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public delete partners" on public.partners for delete to anon using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "TMPCL public select contact enquiries" on public.contact_enquiries for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public insert contact enquiries" on public.contact_enquiries for insert to anon with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "TMPCL public select partner enquiries" on public.partner_enquiries for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public insert partner enquiries" on public.partner_enquiries for insert to anon with check (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "TMPCL public select leadership" on public.leadership_panel for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public insert leadership" on public.leadership_panel for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public update leadership" on public.leadership_panel for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public delete leadership" on public.leadership_panel for delete to anon using (true);
exception when duplicate_object then null; end $$;


-- Website footer/contact settings
create table if not exists public.site_settings (
  id text primary key default 'main',
  footer_phone text default '+91 70000 12345',
  footer_whatsapp text default '917000012345',
  footer_email text default 'info@tmpcl.com',
  footer_location text default 'Bhopal, Madhya Pradesh',
  footer_social_text text default 'Instagram · YouTube · Facebook',
  updated_at timestamptz default now()
);

alter table public.site_settings enable row level security;

do $$ begin
  create policy "TMPCL public select site settings" on public.site_settings for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public insert site settings" on public.site_settings for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public update site settings" on public.site_settings for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;

insert into public.site_settings (id, footer_phone, footer_whatsapp, footer_email, footer_location, footer_social_text)
values ('main', '+91 70000 12345', '917000012345', 'info@tmpcl.com', 'Bhopal, Madhya Pradesh', 'Instagram · YouTube · Facebook')
on conflict (id) do nothing;

-- Public storage buckets
insert into storage.buckets (id, name, public) values
  ('player-photos', 'player-photos', true),
  ('id-proofs', 'id-proofs', true),
  ('team-logos', 'team-logos', true),
  ('squad-banners', 'squad-banners', true),
  ('gallery-media', 'gallery-media', true),
  ('partner-logos', 'partner-logos', true),
  ('leadership-photos', 'leadership-photos', true),
  ('news-images', 'news-images', true)
on conflict (id) do update set public = excluded.public;

do $$ begin
  create policy "TMPCL public read storage" on storage.objects for select to anon using (bucket_id in ('player-photos','id-proofs','team-logos','squad-banners','gallery-media','partner-logos','leadership-photos','news-images'));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public upload storage" on storage.objects for insert to anon with check (bucket_id in ('player-photos','id-proofs','team-logos','squad-banners','gallery-media','partner-logos','leadership-photos','news-images'));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public update storage" on storage.objects for update to anon using (bucket_id in ('player-photos','id-proofs','team-logos','squad-banners','gallery-media','partner-logos','leadership-photos','news-images')) with check (bucket_id in ('player-photos','id-proofs','team-logos','squad-banners','gallery-media','partner-logos','leadership-photos','news-images'));
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "TMPCL public delete storage" on storage.objects for delete to anon using (bucket_id in ('player-photos','id-proofs','team-logos','squad-banners','gallery-media','partner-logos','leadership-photos','news-images'));
exception when duplicate_object then null; end $$;

-- Starter data
insert into public.news_updates (id, title, tag, date, summary)
values ('news-opening-ceremony-01-jun', 'TMPCL Opening Ceremony on 01 June', 'Opening Ceremony', '2026-06-01', 'TMPCL ki grand opening ceremony 01 June ko hogi. League updates, team presentation aur event moments yahin publish honge.')
on conflict (id) do nothing;

insert into public.teams (id, name, city, owner, status)
values
  ('team-bhopal', 'Bhopal Strikers', 'Bhopal', 'Captain Coming Soon', 'Player Auction Pending'),
  ('team-indore', 'Indore Warriors', 'Indore', 'Captain Coming Soon', 'Player Auction Pending'),
  ('team-gwalior', 'Gwalior Royals', 'Gwalior', 'Captain Coming Soon', 'Player Auction Pending')
on conflict (id) do nothing;

-- Default leadership, selection panel and brand ambassador profiles.
-- These are safe placeholder records. TMPCL Team Dashboard se edit/delete kiye ja sakte hain.
insert into public.leadership_panel (id, name, type, designation, bio)
values
  ('leader-founder', 'Founder Name', 'Founder & League Owner', 'Founder & League Owner, TMPCL', 'TMPCL ka mission Madhya Pradesh ke tennis ball cricket talent ko professional trials, player auction aur league platform ke through bada stage dena hai.'),
  ('leader-brand-ambassador-1', 'Brand Ambassador 1', 'Brand Ambassador', 'Brand Ambassador, TMPCL', 'TMPCL ke official brand face ke roop me Madhya Pradesh ke tennis ball cricket talent mission ko support karenge.'),
  ('leader-brand-ambassador-2', 'Brand Ambassador 2', 'Brand Ambassador', 'Brand Ambassador, TMPCL', 'TMPCL ki energy, sportsmanship aur player recognition mission ko represent karenge.'),
  ('leader-head-selector', 'Head Selector Name', 'Head Selector', 'Head Selector, TMPCL Selection Committee', 'Trials me performance, fitness, game awareness aur potential ke basis par player evaluation aur category grading manage karenge.'),
  ('leader-selector-1', 'Selector Name', 'Selector', 'Selector, TMPCL Selection Committee', 'Player shortlisting, category grading aur player auction pool preparation me support karenge.')
on conflict (id) do nothing;
